### ISSUE TITLE
Status update?

### ISSUE THREAD

**Issue by metasoarous** [thheller/shadow-cljsjs#16]
Hello.

What's the status of this project? Does this actually work, and if so how do you use it? I'm trying to figure out what Shadow can and cannot do to see if I want to use it for a project, and can't make much of the state of this project from the README.

Thanks!

**Comment by thheller** [comment]
Uhm this is a helper library used by shadow-cljs to provide easier migration away from CLJSJS. See https://shadow-cljs.github.io/docs/UsersGuide.html#cljsjs for more info.

Not sure what you are looking for here? Usually you will not use this library directly in any way.

**Comment by metasoarous** [comment]
@thheller Thanks for the rapid response! And sorry for the noise; I eventually found that reference and have a better sense of things now.
